channels:
  - conda-forge
  - anaconda
  - schrodinger
  - speleo3
dependencies:
  - jupyter-server-proxy>=1.4
  - pip
  - websockify
  - libglu
  - glew
  - pymol
  - pymol-psico
  - biopython
  - csb
  - pip:
      - .
      - rna-tools
